### ISSUE TITLE
Jumping back a revision makes Vizy unusable - results in JSON

### ISSUE THREAD

**Issue by mattbloomfield** [verbb/vizy#94] opened 2022-01-05 22:58 UTC
**Description**

I was hoping to jump back in time on this page but the vizy block ended up totally borked. 

![image](https://user-images.githubusercontent.com/37582550/148301381-8d50b1ed-b452-4289-8b67-793be95dbe50.png)

**Steps to reproduce**
1. Create a vizy field
2. Add it to an entry type
3. Publish it
4. Make changes, publish again
5. Try to jump back a revision
6. In the revision viewer it looks good! 
7. Once you apply the revision, it comes back as JSON. 

**Additional info**
- Plugin version: 1.0.8
- Craft version: Pro 3.7.26
- Multi-site: Yes or [ No ]

**Additional context**

**Comment by mattbloomfield** [comment] 2022-01-06 14:06
I wanted to add that it also kills the frontend. Luckily I did this in dev but if I had tried in production my site would be irreversibly borked unless I did an actual database recovery.

**Comment by engram-design** [comment] 2022-01-09 22:10
I can't reproduce this one sorry, strange. Did you make any changed to the field between applying revisions? There's likely a JS error on the page, and too late to look at what it was now.

If you're able to reproduce it again (locally - ideally) I'd love to get some more information about the error. Or, if you're able to send through the JSON content from the `content` database table for that field. It may very well be a combination of your block types, fields or content.

**Comment by mattbloomfield** [comment] 2022-01-09 22:32
Weird... I should have tested this a few more times perhaps. I just tried to recreate it locally and didn't get the same issue (https://www.loom.com/share/e22dfb76bd0546ab9983867fef7e9bb4?from_recorder=1&focus_title=1) 

So... I'm happy to be wrong! Hopefully this doesn't bite us going forward. 

Love Vizy btw! We were nervous to use it as it was pretty new when we started building our site (early summer 2021) but man, it's killer! It supports almost all of uschamber.com at this point.

**Comment by engram-design** [comment] 2022-01-09 22:37
Hmmm, I'll continue to test a few more scenarios, fields and block configurations just to be sure. I'm wondering if the entry in your video was the exact same one with the issue in the first place? I wonder if a `max_post_size` or `max_input_vars` limit might've been hit, as your entry content does look quite large?

Thanks for confirming, and glad you are liking it!

**Comment by mattbloomfield** [comment] 2022-01-09 22:41
I thought about that as well - typically when I've seen that on other sites you get a CraftCMS error in the network tab... But it's true we haven't bumped that beyond the standard for this site. If I see it again I'll let you know.

And yes, it was this entry. It's our homepage and is quite large.

**Comment by mattbloomfield** [comment] 2022-01-19 23:25
Posting here as I am seeing the JSON again. This time there was no revision restore, but I did catch the console errors if helpful. 
![image](https://user-images.githubusercontent.com/37582550/150234576-224c1ca4-e373-47fa-8b40-608609f093c0.png)

**Comment by engram-design** [comment] 2022-01-22 07:54
Is that a consistent error, or just happens sometimes? Understood you haven't reverted to a revision, just loading the page.

**Comment by mattbloomfield** [comment] 2022-01-22 08:51
In this case it came up randomly, but persisted with each page load. Not sure of the cause but it left me totally blocked. Luckily it was a Dev environment so nbd

**Comment by engram-design** [comment] 2023-03-29 09:57
Closing due to age and unable to reproduce.

**Closed as completed by engram-design** 2023-03-29 09:57 UTC
